### ISSUE TITLE
OAuth redirect can't log in after logging out in current session

### ISSUE THREAD

**Issue by TonyRL** [RSSNext/Follow#167]
## Environment

Windows 10 21H2, follow app v0.0.1-alpha.1

## Steps to reproduce

1. Log in follow (GitHub)
2. Log out follow
3. Sign in again (GitHub)
4. Wait for redirecting or Press Open Follow
5. App still asks for sign in

## Current workaround

Close follow app and reopen it to log in

**Comment by Innei** [comment]
Is this still a problem?

**Comment by TonyRL** [comment]
Still happening in v0.0.1-alpha.6

**Comment by Innei** [comment]
Can you provide the screen record?

**Comment by TonyRL** [comment]
<details>
<summary>Screen record</summary>

![Screen record](https://github.com/user-attachments/assets/0c802eeb-fbcd-4913-b6c7-90eabac6edd9)
</details>

**Comment by Innei** [comment]
Can you use devtools to see if the request message returned a 401?

**Comment by TonyRL** [comment]
API requests seem normal.

<details>
<summary>Screenshot</summary>

![Screenshot](https://github.com/user-attachments/assets/b343686c-243b-49c9-a3fc-81fb488fc337)
</details>

**Comment by Innei** [comment]
Please provide the Electron's request, not the browser's. You can open devtools with Control(Meta) + Alt + I

**Comment by TonyRL** [comment]
Devtools didn't show up. (It should be Control + Shift + I for Windows)

**Comment by TonyRL** [comment]
> Can you use devtools to see if the request message returned a 401?

Yes

<details>
<summary>Remote debugging</summary>

![devtools](https://github.com/user-attachments/assets/b18cb882-d2af-4664-b679-02830bc55530)
</details>

**Comment by hyoban** [comment]
This should be fixed in https://github.com/RSSNext/Follow/commit/a281f58a811213d933585280238fec4088ad7749, you can try https://github.com/RSSNext/Follow/actions/runs/10919920072

Feel free to open this issue again if you still have questions

**Comment by TonyRL** [comment]
This issue still exists in build 0bcbf0b

<details>
<summary>Screen record</summary>

![2024-09-18](https://github.com/user-attachments/assets/985b07c0-97af-4fa4-b807-e90133885860)
</details>

**Comment by DIYgod** [comment]
Fixed in https://github.com/RSSNext/Follow/commit/80515f67652a77fbdbe20a2a3298fd916515a8d7
