### ISSUE TITLE
GitHub login creates a new account and cannot log in to the previous account

### ISSUE THREAD

**Issue by Windelly** [RSSNext/Follow#2131]
### Describe the bug

I just login with my Github account and get access to app.follow.is today. I didn't got a Invitation Code so I skip that part.
Later, I got an Invitation Code and input it in Preferences-Invitation. It worked,I add dozens of feeds.

Later I login with another device with the same Github account.But It seems that I have to activate my account from the beginning.I still have to input a invite code, and I lost all my feeds.

### Feed Info

It's not a issue about feeds.It's about account.

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Windelly** [comment]
I log in with my Github account with my two devices, each device has to activate the account again.the Power addresses of my two devices are also different.

**Comment by hyoban** [comment]
You may have modified the email address bound to GitHub. Try changing the email back to the account you need to use.

**Comment by Windelly** [comment]
> You may have changed the email address bound to GitHub. Try changing the email back to the account you need to use.

I didn't change the email address bound to GitHub for years.

One more thing , my handle (Preferences-Profile-Handle) is empty, and when I tried to fill it and submit, I got:
[PATCH] "https://api.follow.is/auth-app/update-account": 404

**Comment by iWangJiaxiang** [comment]
> > You may have changed the email address bound to GitHub. Try changing the email back to the account you need to use.
> 
> I didn't change the email address bound to GitHub for years.
> 
> Today I check the first divice I logged on. The account is activated invited and all my feeds are back. One more thing , my handle (Preferences-Profile-Handle) is empty, and when I tried to fill it and submit, I got: [PATCH] "https://api.follow.is/auth-app/update-account": 404

Got same error as well

**Comment by hyoban** [comment]
Update account error is fixed in https://github.com/RSSNext/Follow/commit/aeaf79522be23abb64ae940a4377a92448dfd923

**Comment by wakHitsz** [comment]
Today, I arrived at a different location and used a different IP address. Now, I have lost all my subscription sources and it shows as not activated. Seems like this bug still hasn't been resolved?

> Update account error is fixed in [aeaf795](https://github.com/RSSNext/Follow/commit/aeaf79522be23abb64ae940a4377a92448dfd923)

**Comment by wakHitsz** [comment]
When I logged into the Follow from GitHub, I got a message saying 'Failed to get voice'.

**Comment by hyoban** [comment]
Please try to adjust the email address bound to follow to the first email address bound to GitHub before logging in (setting it as the primary email address has no effect)

**Comment by hyoban** [comment]
We will soon support logging in via email and password

**Comment by stelvetica** [comment]
There is only one email for GitHub, but the login is still empty.

**Comment by Windelly** [comment]
I lost my account and Invitation Code T_T
I find that my Email in github was Windelly@qq.com,but my email in follow was windelly@qq.com.Maybe that's the reason I got a new account when I tried to login another device via Github.
I changed the Email in github and login again,now I got a new account and lost all my feed and Invitation Code.
I backed up my feed.Can I get a new Invitation Code?

**Comment by Windelly** [comment]
My old unique Identifier was empty
