### ISSUE TITLE
Social media view, floating button has an overlap phenomenon

### ISSUE THREAD

**Issue by Waioot** [RSSNext/Follow#2289]
### Describe the bug

Under the social media view, when the author name is too long, .
Under the social media view, when the author's name is too long, it overlaps with the floating button.

<img width="807" alt="Image" src="https://github.com/user-attachments/assets/3fc76754-c727-457a-af18-de17fa59db2a" />
<img width="673" alt="Image" src="https://github.com/user-attachments/assets/e40b912e-8997-41a8-afe7-ee2047267e0a" />

### Feed Info

https://t.me/FindBlog/559

### Environment

Beta Version （E00D952）

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Waioot** [comment]
The issue still exists in the Beta version (871DBF3).

<img width="871" alt="Image" src="https://github.com/user-attachments/assets/b0f9c685-1824-4779-bd4d-1df28ce259a9" />

**Comment by DIYgod** [comment]
Fixed in [v0.3.1-beta.0](https://github.com/RSSNext/Follow/releases/tag/v0.3.1-beta.0)

**Comment by Waioot** [comment]
Occlusion of text still exists

<img width="738" alt="Image" src="https://github.com/user-attachments/assets/a83e5b07-dc8c-47a6-8c07-f937b4e44f33" />
